---
dependencies:
  - role: 0x0i.systemd
    tags: ['never']

galaxy_info:
  author: Ahmad Wilson
  role_name: elasticsearch
  description: Elasticsearch, a real-time distributed search and analytics engine
  company: "O1.IO"
  license: license (MIT)
  min_ansible_version: 2.5
  platforms:
    - name: EL
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - elasticsearch
    - search
    - data
    - analytics
