---
dependencies:
  - role: 0x0i.systemd
    tags: ['never']

galaxy_info:
  author: Ahmad Wilson
  role_name: phoronix
  description: phoronix-test-suite, a comprehensive testing and benchmarking platform
  company: "O1.IO"
  license: MIT License
  min_ansible_version: 2.5
  platforms:
    - name: EL
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

  galaxy_tags:
    - benchmark
    - testing
    - hardware
    - performance
    - phoronix
