---
galaxy_info:
  author: O1 Labs
  role_name: geth
  description: O1 Labs Monitoring services
  company: "O1.IO"
  license: MIT
  min_ansible_version: 2.5
  platforms:
    - name: Debian
      versions:
        - jessie
        - stretch
    - name: Ubuntu
      versions:
        - xenial
        - bionic
        - cosmic
  galaxy_tags:
    - monitoring
    - observability
    - prometheus
    - grafana
    - loki
    - promtail
