---
dependencies:
  - 0x0i.systemd

galaxy_info:
  author: Ahmad Wilson
  role_name: zcashd
  description: zcashd, a client for the Zcash privacy blockchain and protocol
  company: "O1.IO"
  license: license (Apache, BSD, MIT)
  min_ansible_version: 2.5
  platforms:
    - name: EL
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - zcash
    - privacy
    - blockchain
    - zec
    - cryptocurrency
